### ISSUE TITLE
Implement the remote data source

### ISSUE THREAD

**Issue by Diogo00dev** [novoda/multiplatform-playground#12]
Implement the remote data source

The API we are going to use is this one.
https://newsapi.org/

For now we will focus on the endpoint TopHeadlines (/v2/top-headlines) and we will use the country parameter set to "us".
i.e.: https://newsapi.org/v2/top-headlines?country=us&apiKey=XYZ

More customisation will be added at a later date like specifying the **country**, **category** or **sources** 

More info can be found here: https://newsapi.org/docs/endpoints/top-headlines

**Comment by juankysoriano** [comment]
Hey @Diogo00dev could you provide a short description about the API that we are planning to use? At least pointing to the documentation :)

**Comment by Diogo00dev** [comment]
@juankysoriano this is the API I want to use.
https://newsapi.org/
Will write up a readme on Monday
